language: python
sudo: false
cache:
  apt: true
  directories:
    - $HOME/.cache/pip

python:
  - "2.7"

addons:
  apt:
# only add the two lines below if you need wkhtmltopdf for your tests
#    sources:
#      - pov-wkhtmltopdf
#    Search your sources alias here:
#      https://github.com/travis-ci/apt-source-whitelist/blob/master/ubuntu.json
    packages:
      - expect-dev  # provides unbuffer utility
      - python-lxml  # because pip installation is slow
      - python-simplejson
      - python-serial
      - python-yaml
#     Search your packages here:
#       https://github.com/travis-ci/apt-package-whitelist/blob/master/ubuntu-precise
#      - wkhtmltopdf  # only add if needed and check the before_install section below

# set up an X server to run wkhtmltopdf.
#before_install:
#  - "export DISPLAY=:99.0"
#  - "sh -e /etc/init.d/xvfb start"

env:
  global:
  - VERSION="8.0" TESTS="0" LINT_CHECK="0" TRANSIFEX="0"
  - TRANSIFEX_USER='jjscarafia'
  # to get secure, run 'travis encrypt TRANSIFEX_PASSWORD=[transifex_password] -r [github_repo]'
  # example of github repo 'ingadhoc/odoo-infrastructure'
  - secure: x9PaU4KG0TX2KZkhKoHLJWCMbd67TWW5M7Wn1mzyXEyoNUdC2Sob+0nPHMiMbWy2OU3mutruJsyvXAhJGNwQTNerBzsskqWFfa28XNm0/HhVpUSRjBVDLSvbcSp2OS4AFRitBh3wNyPGgIW3MGTkY/Va+MoTqZfZRAg+2CdkVcgPfcATZyXOqYQjCtuLfNGlBouiLQwzZjstVoSG4iQvIuOBlUcXSJtxYjUt2rkT52lo9v5i1x3WH43sKZdS3+kKG/94de4dh6sUbaa7u+hgbaE44ccIy06NrjhyxAzrHOWbHngmSpSd1A/fQfJfBtDU/dNJnfENWYG29r2qNCPAPWuTlkL/EXstTNL2CsezYZ7iRWrtm5c4POmNWFMCOKali03XTaIK/BaIiRiGwErXfjvhOPLQoHyMD0QJyYu1fCfuZ3PuZGFoOv0XKhboixijiL0cTvLLVM4kyoNqhnF2CDpVNFcX2Yn99BlHGt6993rzMNvIdWTPa4iEKrqRogxhQO0UBEdyppyRJHMwG0iWJ4fLVP8LJ46hqfLKNJ8CNAQxaAfD5cA5Cog6s5VOO+DpPd43L4Qw4G/ekwGLwfcd/2W8orEGhw3VJaT4646Y9+mz7EpKiMteANy+8oPyiq0WYc9KhlVd6myayrczcPJQtYWPPoje9kFOJWQ/e+OvAKg=
  - TRANSIFEX_ORGANIZATION='adhoc'
  - TRANSIFEX_TEAM='46451'

  matrix:
  # TODO enable lint check
  #- LINT_CHECK="1"
  - TRANSIFEX="1"
  - TESTS="1" ODOO_REPO="odoo/odoo" 
# either use the two lines above or the two below. Don't change the default if
# it's not necessary (it is only necessary if modules in your repository can't
# be installed in the same database. And you get a huge speed penalty in your
# tests)
#  - TESTS="1.0" ODOO_REPO="odoo/odoo" UNIT_TEST="1"
#  - TESTS="1.0" ODOO_REPO="OCA/OCB" UNIT_TEST="1"

virtualenv:
  system_site_packages: true

install:
  # repository requirements
  - pip install -r requirements.txt

  - git clone --depth=1 https://github.com/OCA/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - travis_install_nightly

script:
  - travis_run_tests

after_success:
  - travis_after_tests_success
